/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.sql.*;
import java.text.ParseException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ELCOT
 */


public class borrow extends javax.swing.JFrame {

    /**
     * Creates new form borrow
     */
    
    public borrow() {
        initComponents();
        tab();
    }
public  int app=0;
 private boolean isBidExits(String Id){
            try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
            PreparedStatement st=con.prepareStatement("select count(*) from borrow where bid=?");
            st.setString(1,Id);
            ResultSet rs=st.executeQuery();
            if(rs.next()){
                  return rs.getInt(1)>0;  
            }
        }catch(ClassNotFoundException | SQLException e){
                   JOptionPane.showMessageDialog(this,e );
        }
            return false;
     }
 public void clear(){
 bid.setText("");
 studentname.setText("");
 bookname.setText("");
 dateborrow.setDate(null);
 datereturn.setDate(null);
}
 public void tab(){
  try{
                  
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
             PreparedStatement st=con.prepareStatement("select bid,stdname,bname,date_borrow,date_return from borrow");
             ResultSet rs=st.executeQuery();
             
           DefaultTableModel m=(DefaultTableModel)table.getModel();
              m.setRowCount(0);
            while(rs.next()){
               
              m.addRow(new Object[]{rs.getString("bid"),rs.getString("stdname"),rs.getString("bname"),rs.getString("date_borrow"),(rs.getString("date_return"))});
               
       }
        }catch(HeadlessException | ClassNotFoundException | SQLException e)
       {JOptionPane.showMessageDialog(this,e);}
}
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    SimpleDateFormat dt=new SimpleDateFormat("yyyy-MM-dd");
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        close = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        insert = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        studentname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bookname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateborrow = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        datereturn = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BORROW");
        setMinimumSize(new java.awt.Dimension(800, 700));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 31)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/borrow.jpeg"))); // NOI18N
        jLabel1.setText("BORROW DETAILS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel1)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 859, -1));

        table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BOOK ID", "STUDENT NAME", "BOOK NAME", "DATE_BORROW", "DATE_RETURN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAlignmentX(3.0F);
        table.setAlignmentY(5.0F);
        table.setRowHeight(40);
        table.setSelectionBackground(new java.awt.Color(51, 0, 51));
        table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 417, 847, 250));

        update.setBackground(new java.awt.Color(255, 153, 102));
        update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 350, -1, -1));

        delete.setBackground(new java.awt.Color(255, 51, 51));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 350, -1, -1));

        close.setBackground(new java.awt.Color(204, 51, 0));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 350, -1, -1));

        reset.setBackground(new java.awt.Color(255, 0, 0));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 350, -1, -1));

        insert.setBackground(new java.awt.Color(51, 51, 255));
        insert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        insert.setText("INSERT");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        getContentPane().add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("BOOK ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 127, 116, 33));

        bid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 127, 197, 33));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("STUDENT NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 191, 116, 33));

        studentname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(studentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 191, 197, 33));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("BOOK NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 257, 116, 33));

        bookname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(bookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 257, 197, 33));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("DATE_BORROW");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 191, 118, 33));
        getContentPane().add(dateborrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 191, 221, 33));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("DATE_RETURN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 257, 118, 33));
        getContentPane().add(datereturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 257, 221, 33));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg8.jpeg"))); // NOI18N
        jLabel8.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jLabel8ComponentShown(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 860, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
       new borrow().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        String Id=bid.getText();
        String Sname=studentname.getText();
        String Bname=bookname.getText();
        
        String Bdate=dt.format(dateborrow.getDate());
        String Rdate=dt.format(datereturn.getDate());        
        if(!Id.isEmpty() && !Sname.isEmpty() && !Bname.isEmpty()){
           if(!isBidExits(Id)){
       try{
            Date db=dt.parse((String)Bdate);
           Date dr=dt.parse((String)Rdate);
            if(db.before(dr)){ 
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
            PreparedStatement pst=con.prepareStatement("insert into borrow (bid,stdname,bname,date_borrow,date_return) values(?,?,?,?,?)");
            pst.setString(1,Id);
            pst.setString(2,Sname);
            pst.setString(3,Bname);
            pst.setString(4,Bdate);
            pst.setString(5,Rdate);
            int a=pst.executeUpdate();
            if(a!=0){
                    JOptionPane.showMessageDialog(this,"DETAILS INSERTED ......");
                    clear();
                    tab();
                    }
             }else{
                     JOptionPane.showMessageDialog(this,"PLEASE ENTER VALID DATE TO RETURN DATE GRATERTHEN TO BORROW DATE ...");
                   }
           }catch(HeadlessException | ClassNotFoundException | SQLException e){JOptionPane.showMessageDialog(this,e);} catch (ParseException ex) 
           {
                Logger.getLogger(borrow.class.getName()).log(Level.SEVERE, null, ex);
            }
       }else{
                JOptionPane.showMessageDialog(this,"THIS ID ALREADY EXITS,PLEASE ENTER VALID ID !!");
                tab();
           }
        }
        else{
            JOptionPane.showMessageDialog(this,"PLEASE ENTER ALL FIELDS !!!");
        }
    }//GEN-LAST:event_insertActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String Id=bid.getText();
        String Sname=studentname.getText();
        String Bname=bookname.getText();
        String Bdate=dt.format(dateborrow.getDate());
        String Rdate=dt.format(datereturn.getDate());
        try{
             Date db=dt.parse((String)Bdate);
           Date dr=dt.parse((String)Rdate);
            if(db.before(dr)){ 
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
            PreparedStatement pst=con.prepareStatement("update borrow  set stdname=?,bname=?,date_borrow=?,date_return=? where bid=?");
            pst.setString(1,Sname);
            pst.setString(2,Bname);
            pst.setString(3,Bdate);
            pst.setString(4,Rdate);
            pst.setString(5,Id);
            int a=pst.executeUpdate();
            
            if(a!=0){
                           JOptionPane.showMessageDialog(this,"DETAILS UPDATED......");
                           clear();
                           tab();
               } 
            }else{
                     JOptionPane.showMessageDialog(this,"PLEASE ENTER VALID DATE TO RETURN DATE GRATERTHEN TO BORROW DATE ...");
                    
                     }
        }catch(HeadlessException | ClassNotFoundException | SQLException e){JOptionPane.showMessageDialog(this,e);} catch (ParseException ex) {
            Logger.getLogger(borrow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         int a=JOptionPane.showConfirmDialog(this,"DO YOU WANT DELETE ?","SELECT",JOptionPane.YES_NO_OPTION);
        String Id=bid.getText();
        try{
            
            if(a==0){
          Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
             PreparedStatement pst=con.prepareStatement("delete from borrow where bid=?");
            pst.setString(1, Id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"THIS BOOK IS DELETED....");
            clear();
            tab();
          }
        }catch(HeadlessException | ClassNotFoundException | SQLException e){JOptionPane.showMessageDialog(this,e);}
       
    }//GEN-LAST:event_deleteActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void jLabel8ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel8ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8ComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        update.setEnabled(false);
        delete.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int index=table.getSelectedRow();
        TableModel m=table.getModel();
         String Id=m.getValueAt(index,0).toString();
         app=Integer.parseInt(Id);
         bid.setText(Id);
         
         String Name=m.getValueAt(index, 1).toString();
         studentname.setText(Name);
          String Bname=m.getValueAt(index, 2).toString();
         bookname.setText(Bname);
        
        try {
            Date Dateborrow=dt.parse((String)m.getValueAt(index,3));
            dateborrow.setDate(Dateborrow);
            Date Datereturn=dt.parse((String)m.getValueAt(index,4));
            datereturn.setDate(Datereturn);
        } catch (ParseException ex) {
            Logger.getLogger(borrow.class.getName()).log(Level.SEVERE, null, ex);
        }
        insert.setEnabled(false);
        update.setEnabled(true);
        delete.setEnabled(true);
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(borrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new borrow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bid;
    private javax.swing.JTextField bookname;
    private javax.swing.JButton close;
    private com.toedter.calendar.JDateChooser dateborrow;
    private com.toedter.calendar.JDateChooser datereturn;
    private javax.swing.JButton delete;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reset;
    private javax.swing.JTextField studentname;
    private javax.swing.JTable table;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
