/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

/**
 *
 * @author ELCOT
 */
import java.awt.HeadlessException;
import java.sql.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
public class librarian extends javax.swing.JFrame {

    /**
     * Creates new form librarian
     */
    public librarian() {
        initComponents();
        tab();
    }
     private static final String EMAIL_REGEX="^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,3}$";
public static boolean isValidEmail(String Em){
     return Pattern.matches(EMAIL_REGEX,Em);
     }
 public int app=0;
 private boolean isIdExits(String Id){
            try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
            PreparedStatement st=con.prepareStatement("select count(*) from librarian where id=?");
            st.setString(1,Id);
            ResultSet rs=st.executeQuery();
            if(rs.next()){
                  return rs.getInt(1)>0;  
            }
        }catch(ClassNotFoundException | SQLException e){
                   JOptionPane.showMessageDialog(this,e );
        }
            return false;
     }
 public void tab(){
 try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
             PreparedStatement st=con.prepareStatement("select id,name,email,address from librarian ");
             ResultSet rs=st.executeQuery();
             
           DefaultTableModel m=(DefaultTableModel)table.getModel();
           m.setRowCount(0);
           while(rs.next()){
              m.addRow(new Object[]{rs.getString("id"),rs.getString("name"),rs.getString("email"),rs.getString("address")});
               }
                 
        }catch(HeadlessException | ClassNotFoundException | SQLException e)
        {JOptionPane.showMessageDialog(this,e);}
 
 }
 public void clear(){
 libid.setText("");
 name.setText("");
 email.setText("");
 address.setText("");
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        libid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        close = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LIBRARIAN");
        setMinimumSize(new java.awt.Dimension(794, 650));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 31)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login.png"))); // NOI18N
        jLabel1.setText("LIBRARIAN DETAILS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel1)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 110));

        table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LIB.ID", "NAME", "EMAIL ID", "ADDRESS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAlignmentX(3.0F);
        table.setAlignmentY(5.0F);
        table.setRowHeight(40);
        table.setSelectionBackground(new java.awt.Color(51, 0, 51));
        table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 780, 194));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 51));
        jLabel3.setText("LIB.ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 120, 129, -1));

        libid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(libid, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 114, 314, 38));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 51));
        jLabel4.setText("NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 189, 129, -1));

        name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 183, 314, 37));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 51));
        jLabel5.setText("ADDRESS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 306, 129, 40));

        address.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 307, 314, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 51));
        jLabel6.setText("EMAIL ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 243, 129, 37));

        email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 243, 314, 37));

        insert.setBackground(new java.awt.Color(51, 51, 255));
        insert.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        insert.setText("INSERT");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        getContentPane().add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 101, 30));

        delete.setBackground(new java.awt.Color(255, 51, 51));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 101, 30));

        close.setBackground(new java.awt.Color(255, 51, 0));
        close.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, -1, 30));

        reset.setBackground(new java.awt.Color(255, 204, 0));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 91, 29));

        update.setBackground(new java.awt.Color(153, 255, 153));
        update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg10.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 800, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new librarian().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        String Id=libid.getText();
        String Name=name.getText();
        String Email=email.getText();
        String Address=address.getText();
        if(!Id.isEmpty() && !Name.isEmpty() && !Email.isEmpty() && !Address.isEmpty()){
         if(!isIdExits(Id)){
            
            try{
              Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
              Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
              PreparedStatement pst=con.prepareStatement("insert into librarian (id,name,email,address) values (?,?,?,?)");
              pst.setString(1,Id);
              pst.setString(2,Name);
              pst.setString(3,Email);
              pst.setString(4,Address);
              int a=pst.executeUpdate();
              if(a!=0){
                        JOptionPane.showMessageDialog(this,"DETAILS INSERTED....");
                        clear();
                        tab();
              }else{
                        JOptionPane.showMessageDialog(this,"ERROR !!!");
              }
        }catch(HeadlessException | ClassNotFoundException | SQLException e){JOptionPane.showMessageDialog(this,e);} 
        }else{
                JOptionPane.showMessageDialog(this,"THIS ID ALREADY EXITS,PLEASE ENTER VALID ID !!");
           }
        }else{JOptionPane.showMessageDialog(this,"PLEASE ENTER ALL FIELDS");}
    }//GEN-LAST:event_insertActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         int a=JOptionPane.showConfirmDialog(this,"DO YOU WANT DELETE ?","SELECT",JOptionPane.YES_NO_OPTION);
        String Id=libid.getText();
        try{
            if(a==0){
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
            PreparedStatement pst=con.prepareStatement("delete from librarian where id=?");
            pst.setString(1, Id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"THIS LIBRARIAN IS DELETED.....");
            clear();
            tab();
          }
        }catch(HeadlessException | ClassNotFoundException | SQLException e){JOptionPane.showMessageDialog(this,e);}
       
    }//GEN-LAST:event_deleteActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        update.setEnabled(false);
        delete.setEnabled(false);
        
    }//GEN-LAST:event_formComponentShown

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int index=table.getSelectedRow();
        TableModel m=table.getModel();
         String Id=m.getValueAt(index,0).toString();
         app=Integer.parseInt(Id);
         libid.setText(Id);
         
         String Name=m.getValueAt(index,1).toString();
         name.setText(Name);
          String Email=m.getValueAt(index,2).toString();
         email.setText(Email);
        String Address=m.getValueAt(index,3).toString();
         address.setText(Address);
       
        insert.setEnabled(false);
        update.setEnabled(true);
        delete.setEnabled(true);
    }//GEN-LAST:event_tableMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         String Id=libid.getText();
        String Name=name.getText();
        String Email=email.getText();
        String Address=address.getText();
          try{
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
            PreparedStatement pst=con.prepareStatement("update librarian set name=?,email=?,address=? where id=?");
              pst.setString(4,Id);
              pst.setString(1,Name);
              pst.setString(2,Email);
              pst.setString(3,Address);
              int a=pst.executeUpdate();
              if(a!=0){
                        JOptionPane.showMessageDialog(this,"DETAILS UPDATED....");
              }else{
                        JOptionPane.showMessageDialog(this,"ERROR !!!");
              }  }catch(HeadlessException | ClassNotFoundException | SQLException e){JOptionPane.showMessageDialog(this,e);} 
        
      
    }//GEN-LAST:event_updateActionPerformed

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
         String Email=email.getText();
        if(!isValidEmail(Email)){
               JOptionPane.showMessageDialog(this,"PLEASE ENTER VALID EMAIL!!");
               return;
             }
    }//GEN-LAST:event_emailFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new librarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField libid;
    private javax.swing.JTextField name;
    private javax.swing.JButton reset;
    private javax.swing.JTable table;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
