/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ELCOT
 */
public class student extends javax.swing.JFrame {

    /**
     * Creates new form student
     */
    public student() {
        initComponents();
        increment();
        tab();
    }
   private static final String PHONE_REGEX = "^\\d{10}$";
      private static final String EMAIL_REGEX="^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,3}$";
public static boolean isValidEmail(String Em){
     return Pattern.matches(EMAIL_REGEX,Em);
     }
 public static boolean isValidPhone(String Num) {
        return Pattern.matches(PHONE_REGEX, Num);
    }
     
      public  File selectedFile;
 public FileInputStream file;
 public String filename;
 public byte[] oldImageBytes;

  
  private boolean isIdExits(String Id){
            try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
            PreparedStatement st=con.prepareStatement("select count(*) from managestudent where id=?");
            st.setString(1,Id);
            ResultSet rs=st.executeQuery();
            if(rs.next()){
                  return rs.getInt(1)>0;  
            }
        }catch(ClassNotFoundException | SQLException e){
                   JOptionPane.showMessageDialog(this,e );
        }
            return false;
     }
  public void increment(){
   try{
       
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
              PreparedStatement pst=con.prepareStatement("select max(id) from managestudent");
            ResultSet rs=pst.executeQuery();
        rs.next();
        String Mid=rs.getString(1);
            if(Mid==null){
             sid.setText("ST001");
            }
            else{
            int Cid=Integer.parseInt(Mid.substring(2));
            Cid++;
            sid.setText(String.format("ST%03d",Cid));
            }
    
      }catch(Exception e){JOptionPane.showMessageDialog(null,e);
    
      }
    
    }
  public void tab(){
   try{
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
              PreparedStatement pst=con.prepareStatement("select count(id) as ids from managestudent");
            PreparedStatement st=con.prepareStatement("sp_stud_getall");
            ResultSet rs=pst.executeQuery();
            ResultSet dt=st.executeQuery();
            while(rs.next()){
                      totalstudent.setText(rs.getString("ids"));
            }
             DefaultTableModel m=(DefaultTableModel)table.getModel();
             m.setRowCount(0);
           while(dt.next()){
              m.addRow(new Object[]{dt.getString("id"),dt.getString("name"),dt.getString("email"),dt.getString("phonenumber"),dt.getString("address"),dt.getString("image"),dt.getString("imagename")});
               }
              
            
        }catch(HeadlessException | ClassNotFoundException | SQLException e)
        {JOptionPane.showMessageDialog(this,e);}
  
  }
  public void clear(){
   name.setText("");
   email.setText("");
   number.setText("");
   address.setText("");
   image.setIcon(null);
   imagename.setText("");
  }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        imagename = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        upload = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        totalstudent = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 650));
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setPreferredSize(new java.awt.Dimension(1000, 650));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("STUDENT MANAGEMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("STU.ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 87, 177, 44));

        sid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(sid, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 87, 287, 44));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 143, 177, 44));

        name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 143, 287, 44));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("EMAIL ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 199, 177, 44));

        email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 199, 287, 44));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("PHONE NUMBER");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 255, 177, 44));

        number.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numberFocusLost(evt);
            }
        });
        getContentPane().add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 255, 287, 44));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setText("ADDRESS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 87, 153, 44));

        address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 87, 287, 44));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 102));
        jLabel7.setText("IMAGENAME");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 261, 153, 44));

        imagename.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(imagename, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 261, 287, 44));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 102));
        jLabel8.setText("IMAGE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 143, 153, 44));

        image.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        image.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 143, 126, 100));

        upload.setBackground(new java.awt.Color(51, 204, 0));
        upload.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        upload.setForeground(new java.awt.Color(0, 0, 102));
        upload.setText("UPLOAD");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        getContentPane().add(upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 212, 112, 31));

        table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENT ID", "NAME", "EMAIL ID", "PHONE NUMBER", "ADDRESS", "IMAGE", "IMAGE NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(40);
        table.setSelectionBackground(new java.awt.Color(51, 0, 51));
        table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 362, 990, 206));

        add.setBackground(new java.awt.Color(0, 0, 102));
        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(153, 255, 255));
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 311, 168, 33));

        edit.setBackground(new java.awt.Color(255, 255, 51));
        edit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edit.setForeground(new java.awt.Color(51, 51, 51));
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 311, 162, 33));

        delete.setBackground(new java.awt.Color(255, 102, 102));
        delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(102, 0, 0));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(698, 311, 168, 33));

        reset.setBackground(new java.awt.Color(255, 204, 0));
        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 102, 51));
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 574, 108, -1));

        close.setBackground(new java.awt.Color(102, 0, 0));
        close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(869, 574, 108, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 102));
        jLabel10.setText("TOTAL STUDENT");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 574, 164, 29));

        totalstudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(totalstudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 574, 143, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/appoinmentimages1.jpeg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 76, 1010, 580));

        setSize(new java.awt.Dimension(1016, 658));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(this,"DO YOU WANT DELETE THIS STUDENT ?","SELECT",JOptionPane.YES_NO_OPTION);
        String Id=sid.getText();

        try{
            if(a==0){
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
                PreparedStatement pst=con.prepareStatement("sp_stud_delete ?");
                pst.setString(1,Id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"THIS STUDENT IS DELETED...");
                clear();
                tab();
                increment();
            }
        }catch(HeadlessException | ClassNotFoundException | SQLException e){JOptionPane.showMessageDialog(this,e);}
    }//GEN-LAST:event_deleteActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        // TODO add your handling code here:
        
        JFileChooser filechooser=new JFileChooser();
        filechooser.addChoosableFileFilter(new FileNameExtensionFilter("image Files","jpg","jpeg","png","gif"));
        int result=filechooser.showOpenDialog(this);
        if(result==JFileChooser.APPROVE_OPTION){
            selectedFile=filechooser.getSelectedFile();
            filename=selectedFile.getName();
            imagename.setText(filename);
            ImageIcon icon=new ImageIcon(selectedFile.getAbsolutePath());
            image.setIcon(new ImageIcon(icon.getImage().getScaledInstance(image.getWidth(),image.getHeight(),Image.SCALE_SMOOTH)));
            JOptionPane.showMessageDialog(this,"IMAGE UPLOADED..");
        }
    }//GEN-LAST:event_uploadActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
         String Id=sid.getText();
        String Name=name.getText();
        String Email=email.getText();
        String Number=number.getText();
        String Address=address.getText();
        System.out.println((int)selectedFile.length());
        String Imagename=imagename.getText();
        if(!Id.isEmpty()&&!Name.isEmpty()&&!Email.isEmpty()&& !Address.isEmpty()){
            if(!isIdExits(Id)){
                try{
                    file=new FileInputStream(selectedFile);
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
                    PreparedStatement pst=con.prepareStatement("sp_stud_insert ?,?,?,?,?,?,?");
                    pst.setString(1,Id);
                    pst.setString(2,Name);
                    pst.setString(3,Email);
                    pst.setString(4,Number);
                    pst.setString(5,Address);
                    pst.setBinaryStream(6,file,(int)selectedFile.length());
                    pst.setString(7,Imagename);
                    int a=pst.executeUpdate();
                    if(a!=0){
                        JOptionPane.showMessageDialog(this,"STUDENT ADDED....");
                        clear();
                        tab();
                        increment();
                    }
                    else{JOptionPane.showMessageDialog(this," FAILED ADD PROCESS!!");}

                }catch(HeadlessException | ClassNotFoundException | SQLException e)
                {JOptionPane.showMessageDialog(this,e);} catch (FileNotFoundException ex) {
                    Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{JOptionPane.showMessageDialog(this,"THIS ID ALREADY EXIT, PLEASE ENTER VALID ID");}
        }else{JOptionPane.showMessageDialog(this,"PLEASE ENTER ALL FIELDS !!!");}
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
          String Id=sid.getText();
        String Name=name.getText();
        String Email=email.getText();
        String Number=number.getText();
        String Address=address.getText();
        String Imagename=imagename.getText();
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
            PreparedStatement pst=con.prepareStatement("sp_stud_update ?,?,?,?,?,?,?");
            pst.setString(1,Id);
            pst.setString(2,Name);
            pst.setString(3,Email);
            pst.setString(4,Number);
            pst.setString(5,Address);
            if(selectedFile!=null){
                file=new FileInputStream(selectedFile);
                pst.setBinaryStream(6,file,(int)selectedFile.length());
            }else if(oldImageBytes!=null){
                pst.setBytes(6,oldImageBytes);
            }else{pst.setNull(6,Types.VARBINARY);}
            pst.setString(7,Imagename);
            int a=pst.executeUpdate();
            if(a!=0){
                JOptionPane.showMessageDialog(this,"UPDATED SUCCESSFULLY.....");
                clear();
                tab();
                increment();
            }
            else{JOptionPane.showMessageDialog(this,"SOMETHING ERROR!!");}
        }catch(HeadlessException | ClassNotFoundException | SQLException e){JOptionPane.showMessageDialog(this,e);} catch (FileNotFoundException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int index=table.getSelectedRow();
        TableModel m=table.getModel();
        sid.setText(m.getValueAt(index, 0).toString());
        name.setText(m.getValueAt(index,1).toString());
        email.setText(m.getValueAt(index,2).toString());
        number.setText(m.getValueAt(index,3).toString());
        address.setText(m.getValueAt(index,4).toString());

        String Id=m.getValueAt(index,0).toString();
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con=DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=librarymanagement;trustServerCertificate=true;user=librarymanage;password=libr");
            PreparedStatement st=con.prepareStatement("select image from  managestudent where id=?");
            st.setString(1,Id);
            ResultSet rs=st.executeQuery();
            if(rs.next()){
                oldImageBytes = rs.getBytes("image");
                ImageIcon icon = new ImageIcon(oldImageBytes);
                image.setIcon(new ImageIcon(icon.getImage().getScaledInstance(image.getWidth(), image.getHeight(), Image.SCALE_SMOOTH)));
            }else{JOptionPane.showMessageDialog(this,"IMAGE NOT FOUND ...");}
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(student.class.getName()).log(Level.SEVERE, null, ex);
        }
        imagename.setText(m.getValueAt(index,6).toString());
        add.setEnabled(false);
        edit.setEnabled(true);
        delete.setEnabled(true);
    }//GEN-LAST:event_tableMouseClicked

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        String Email=email.getText();
        if(!isValidEmail(Email)){
            JOptionPane.showMessageDialog(this,"PLEASE ENTER VALID EMAIL!!");
            return;
        }
    }//GEN-LAST:event_emailFocusLost

    private void numberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numberFocusLost
        // TODO add your handling code here:
        String Number=number.getText();
        if(!isValidPhone(Number)){
            JOptionPane.showMessageDialog(this,"PLEASE ENTER VALID PHONE NUMBER!!");
            return;
        }
    }//GEN-LAST:event_numberFocusLost

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        edit.setEnabled(false);
        delete.setEnabled(false);
        totalstudent.setEditable(false);
    }//GEN-LAST:event_formComponentShown

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new student().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private javax.swing.JButton close;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField email;
    private javax.swing.JLabel image;
    private javax.swing.JTextField imagename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JButton reset;
    private javax.swing.JTextField sid;
    private javax.swing.JTable table;
    private javax.swing.JTextField totalstudent;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables
}
